global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8899']

  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          instance: 'prometheus'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'prometheus_.*'
        action: keep
  
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          instance: 'node'

  - job_name: 'otel-collector'
  static_configs:
    - targets: ['otel-collector:8889']
      labels:
        instance: 'otel-collector'