http:
  middlewares:
    # Compression middleware
    compression:
      compress:
        excludedContentTypes:
          - "image/png"
          - "image/jpeg"
          - "image/gif"
          - "image/webp"
        minResponseBodyBytes: 1024  # Only compress responses larger than 1KB

    # Browser cache middleware
    browser-cache:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=3600"
          Expires: "3600"

    # Buffer middleware for large files
    buffering:
      buffering:
        maxRequestBodyBytes: 10485760  # 10MB
        memRequestBodyBytes: 2097152   # 2MB
        maxResponseBodyBytes: 10485760 # 10MB
        memResponseBodyBytes: 2097152  # 2MB
        retryExpression: "IsNetworkError() && Attempts() <= 2"

    # HTTP/2 optimization headers
    http2-optimize:
      headers:
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "geolocation=(),microphone=(),camera=()"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"